ALTER SESSION SET NLS_LANGUAGE = 'BRAZILIAN PORTUGUESE';
ALTER SESSION SET NLS_TERRITORY = 'BRAZIL';

SELECT DISTINCT 
TO_CHAR(S.LOGON_TIME,'DD/MM/YY HH24:MI') LOGON_TIME, S.OSUSER, S.MACHINE, O.OWNER, O.OBJECT_NAME, 
S.PROGRAM, S.MODULE, DECODE(L.LOCKED_MODE, 1, 'NO LOCK', 2, 'ROW SHARE', 3, 'ROW EXCLUSIVE',
4, 'SHARED TABLE', 5, 'SHARED ROW EXCLUSIVE', 6, 'EXCLUSIVE') LOCKED_MODE, A.SQL_TEXT,
'ALTER SYSTEM KILL SESSION '''||S.SID||',' || S.SERIAL#||',@'||S.INST_ID||''' IMMEDIATE;' ORA_KILLSESSION,
'EXEC RDSADMIN.RDSADMIN_UTIL.KILL('||S.SID||','||S.SERIAL#||','||''''||'IMMEDIATE'||''''||');' AWS_KILLSESSION
FROM GV$LOCKED_OBJECT L 
INNER JOIN GV$LOCK D ON D.SID =L.SESSION_ID
INNER JOIN DBA_OBJECTS O ON L.OBJECT_ID = O.OBJECT_ID 
INNER JOIN GV$SESSION S ON L.INST_ID = S.INST_ID AND L.SESSION_ID = S.SID
INNER JOIN GV$PROCESS P ON S.INST_ID = P.INST_ID AND S.PADDR = P.ADDR
INNER JOIN GV$SQLAREA A ON S.SQL_ADDRESS = A.ADDRESS AND S.SQL_HASH_VALUE=A.HASH_VALUE
ORDER BY O.OWNER, O.OBJECT_NAME;


