
GRANT EXECUTE ON UTL_HTTP   TO APPUTEIS;
GRANT EXECUTE ON UTL_INADDR TO APPUTEIS;
GRANT EXECUTE ON UTL_SMTP   TO APPUTEIS;
GRANT EXECUTE ON UTL_TCP    TO APPUTEIS;

SELECT * FROM DBA_NETWORK_ACLS;

EXECUTE DBMS_NETWORK_ACL_ADMIN.CREATE_ACL (ACL => 'http_mailgd.xml', DESCRIPTION => 'mail', PRINCIPAL => 'APPUTEIS', IS_GRANT => TRUE, PRIVILEGE => 'connect');
COMMIT;

EXECUTE DBMS_NETWORK_ACL_ADMIN.ADD_PRIVILEGE (ACL => 'http_mailgd.xml', PRINCIPAL => 'APPUTEIS',IS_GRANT => TRUE, PRIVILEGE => 'connect');
COMMIT;

EXECUTE DBMS_NETWORK_ACL_ADMIN.ADD_PRIVILEGE (ACL => 'http_mailgd.xml', PRINCIPAL => 'APPUTEIS',IS_GRANT => TRUE, privilege => 'resolve');
COMMIT;

EXECUTE DBMS_NETWORK_ACL_ADMIN.ASSIGN_ACL (ACL => 'http_mailgd.xml', LOWER_PORT => 587, HOST => 'zimbragd.perto.com.br');
COMMIT;

alter system set smtp_out_server = 'zimbragd.perto.com.br:587' scope=both;



