SET LINESIZE 200
SET PAGESIZE 5000

SELECT 'ALTER '||CASE
WHEN TRIM(OBJECT_TYPE) = 'FUNCTION' THEN 'FUNCTION '
WHEN TRIM(OBJECT_TYPE) = 'MATERIALIZED VIEW' THEN 'MATERIALIZED VIEW '
WHEN TRIM(OBJECT_TYPE) = 'PACKAGE' THEN 'PACKAGE '
WHEN TRIM(OBJECT_TYPE) = 'PACKAGE BODY' THEN 'PACKAGE '
WHEN TRIM(OBJECT_TYPE) = 'PROCEDURE' THEN 'PROCEDURE '
WHEN TRIM(OBJECT_TYPE) = 'SYNONYM' THEN 'SYNONYM '
WHEN TRIM(OBJECT_TYPE) = 'TRIGGER' THEN 'TRIGGER '
WHEN TRIM(OBJECT_TYPE) = 'VIEW' THEN 'VIEW '
WHEN TRIM(OBJECT_TYPE) = 'TYPE' THEN 'TYPE '
WHEN TRIM(OBJECT_TYPE) = 'TYPE BODY' THEN 'TYPE '
END
||OWNER||'.'||OBJECT_NAME||' COMPILE;' DDL_COMPILE
FROM DBA_OBJECTS WHERE STATUS = 'INVALID' 
ORDER BY OWNER, OBJECT_TYPE, OBJECT_NAME;
