BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM (DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', TRUE);
  DBMS_METADATA.SET_TRANSFORM_PARAM (DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', TRUE);
  DBMS_METADATA.SET_TRANSFORM_PARAM (DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', FALSE);
  DBMS_METADATA.SET_TRANSFORM_PARAM (DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', FALSE);
END;


SELECT DBMS_METADATA.GET_DDL('PROCOBJ',JOB_NAME,OWNER) SCHEDULER
FROM DBA_SCHEDULER_JOBS
WHERE OWNER NOT IN ('EXFSYS','ORACLE_OCM','SYS','APEX_040200','APEX_050100')
AND ENABLED = 'TRUE'
ORDER BY OWNER, JOB_NAME; 
