SET LINESIZE 1000
COLUMN SID FORMAT 999
COLUMN USERNAME FORMAT A15 
COLUMN SPID FORMAT A8
COLUMN EVENT FORMAT A30 
COLUMN OSUSER FORMAT A12 
COLUMN MACHINE FORMAT A25
COLUMN PROGRAM FORMAT A30
SELECT SW.SID SID,
P.SPID SPID,
S.USERNAME USERNAME,
S.OSUSER OSUSER,
SW.EVENT EVENT,
S.MACHINE MACHINE,
S.PROGRAM PROGRAM,
S.MODULE
FROM V$SESSION_WAIT SW, V$SESSION S, V$PROCESS P
WHERE S.PADDR = P.ADDR
AND S.EVENT NOT IN ('pipe get','client message')
AND SW.SID = S.SID; 
