ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

SELECT TO_CHAR(JD.REQ_START_DATE,'DD/MM/YYYY HH24:MI') DATAHORA,
TO_CHAR(JD.REQ_START_DATE,'DAY') DIASEMANA,  
STATUS, JD.OWNER, JD.JOB_NAME, JD.RUN_DURATION, JD.ADDITIONAL_INFO
FROM SYS.DBA_SCHEDULER_JOB_RUN_DETAILS JD
INNER JOIN DBA_SCHEDULER_JOBS JB ON JB.OWNER = JD.OWNER AND JB.JOB_NAME = JD.JOB_NAME
WHERE JB.OWNER = '' AND JB.JOB_NAME = ''
ORDER BY JD.REQ_START_DATE DESC;
