ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';

SELECT LB.OWNER, LB.TABLE_NAME, LB.COLUMN_NAME, LC.DATA_TYPE, 
TO_CHAR(SG.BYTES/1024/1024,'999G999G999') SIZE_MB
FROM DBA_LOBS LB
INNER JOIN DBA_TAB_COLUMNS LC ON LB.COLUMN_NAME=LC.COLUMN_NAME 
AND LB.TABLE_NAME = LC.TABLE_NAME AND LB.OWNER = LC.OWNER
INNER JOIN DBA_SEGMENTS SG ON LB.OWNER = SG.OWNER AND LB.TABLE_NAME = SG.SEGMENT_NAME
WHERE LB.OWNER NOT IN ('AUDSYS','DBSNMP','CTXSYS','GSMADMIN_INTERNAL','OJVMSYS','OUTLN','SYS','SYSTEM','XDB','WMSYS')
AND LC.DATA_TYPE IN ('CLOB','BLOB')
ORDER BY SIZE_MB DESC; 
