ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
ALTER SESSION SET NLS_LANGUAGE = 'BRAZILIAN PORTUGUESE';
ALTER SESSION SET NLS_TERRITORY = 'BRAZIL';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';
SET LINESIZE 200
SET PAGESIZE 100
SET COLSEP "|"

COLUMN GROUP FORMAT 999
COLUMN DISKGROUP FORMAT A15
COLUMN DISKS FORMAT 999
COLUMN MAXSIZEMB FORMAT 999G999G999
COLUMN USEDMB FORMAT 999G999G999
COLUMN FREEMB FORMAT 999G999G999
COLUMN FREE% FORMAT 999D99
SELECT DG.GROUP_NUMBER "GROUP", DG.NAME "DISKGROUP", DS.ADK "DISKS",
TRIM(TO_CHAR(DG.TOTAL_MB,'999G999G999')) " MAXSIZEMB", 
TRIM(TO_CHAR(DG.COLD_USED_MB,'999G999G999')) " USEDMB",
TRIM(TO_CHAR(DG.FREE_MB,'999G999G999')) " FREEMB",
TO_CHAR(DG.FREE_MB * 100 / DG.TOTAL_MB,'99D99') " FREE%"
FROM V$ASM_DISKGROUP DG JOIN
(SELECT GROUP_NUMBER, COUNT(DISTINCT DISK_NUMBER) ADK
FROM V$ASM_DISK_STAT
WHERE MOUNT_STATUS = 'CACHED'
GROUP BY GROUP_NUMBER) DS
ON (DS.GROUP_NUMBER = DG.GROUP_NUMBER) 
ORDER BY DG.NAME;
			 
