
SELECT OWNER , OBJECT_TYPE, COUNT(*)
FROM DBA_OBJECTS
WHERE OWNER = ''
GROUP BY OWNER, OBJECT_TYPE
ORDER BY OWNER, OBJECT_TYPE;

SELECT NAME FROM V$DATABASE;

SELECT UTL_INADDR.GET_HOST_ADDRESS FROM DUAL;


SELECT 'DROP '||OBJECT_TYPE||' "'||OWNER||'"."'||OBJECT_NAME||'"'||
DECODE(OBJECT_TYPE,'TABLE',' CASCADE CONSTRAINTS;',';')
FROM DBA_OBJECTS
WHERE OWNER = '' 
ORDER BY OWNER, OBJECT_TYPE, OBJECT_NAME;




