Table Stale Statistics

COLUMN TABLE_NAME FOR A30
SELECT LAST_ANALYZED,STATTYPE_LOCKED,TABLE_NAME 
FROM DBA_TAB_STATISTICS 
WHERE OWNER='' AND STALE_STATS ='YES'; 

Index Stale Statistics

SELECT LAST_ANALYZED,INDEX_NAME,STALE_STATS 
FROM DBA_IND_STATISTICS 
WHERE OWNER='' AND STALE_STATS ='YES';

EXEC DBMS_STATS.FLUSH_DATABASE_MONITORING_INFO;

SELECT 	M.TABLE_OWNER, 'NO' AS IS_PARTITION, M.TABLE_NAME AS NAME,		
		M.INSERTS, M.UPDATES, M.DELETES, M.TRUNCATED,
		M.TIMESTAMP AS LAST_MODIFIED,		
		ROUND((M.INSERTS+M.UPDATES+M.DELETES)*100/NULLIF(T.NUM_ROWS,0),2) AS EST_PCT_MODIFIED,
		T.NUM_ROWS AS LAST_KNOWN_ROWS_NUMBER, T.LAST_ANALYZED
FROM 	DBA_TAB_MODIFICATIONS M, DBA_TABLES T		
WHERE 	M.TABLE_OWNER = T.OWNER AND M.TABLE_NAME = T.TABLE_NAME AND M.TABLE_OWNER NOT IN ('SYS','SYSTEM') 
AND 	((M.INSERTS + M.UPDATES + M.DELETES)*100/NULLIF(T.NUM_ROWS,0) > 10 OR T.LAST_ANALYZED IS NULL)
UNION
SELECT 	M.TABLE_OWNER, 'YES' AS IS_PARTITION, M.PARTITION_NAME AS NAME,		
		M.INSERTS, M.UPDATES, M.DELETES, M.TRUNCATED,
		M.TIMESTAMP AS LAST_MODIFIED,		
		ROUND((M.INSERTS+M.UPDATES+M.DELETES)*100/NULLIF(P.NUM_ROWS,0),2) AS EST_PCT_MODIFIED,
		P.NUM_ROWS AS LAST_KNOWN_ROWS_NUMBER, P.LAST_ANALYZED		
FROM 	DBA_TAB_MODIFICATIONS M, DBA_TAB_PARTITIONS P
WHERE 	M.TABLE_OWNER = P.TABLE_OWNER AND	M.TABLE_NAME = P.TABLE_NAME AND M.PARTITION_NAME = P.PARTITION_NAME
AND 	M.TABLE_OWNER NOT IN ('SYS','SYSTEM')
AND 	((M.INSERTS + M.UPDATES + M.DELETES)*100/NULLIF(P.NUM_ROWS,0) > 10 OR P.LAST_ANALYZED IS NULL)
ORDER BY 8 DESC;
