SELECT  (SELECT ROUND (AVG (BYTES) / 1024 / 1024)
FROM  V$LOG) AS "Redo size (MB)",
ROUND ( (20 / AVERAGE_PERIOD) * (SELECT AVG (BYTES) FROM V$LOG) / 1024 / 1024) AS "Recommended Size (MB)"
FROM  (SELECT AVG ( (NEXT_TIME - FIRST_TIME) * 24 * 60) AS  AVERAGE_PERIOD
FROM  V$ARCHIVED_LOG
WHERE FIRST_TIME > SYSDATE - 10  AND TO_CHAR (FIRST_TIME, 'HH24:MI') BETWEEN '01:00' AND '23:00'); 