ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
ALTER SESSION SET NLS_LANGUAGE = 'BRAZILIAN PORTUGUESE';
ALTER SESSION SET NLS_TERRITORY = 'BRAZIL';

SELECT OWNER, JOB_NAME, JOB_TYPE, SUBSTR(JOB_ACTION,1,50) JOB_ACTION, REPEAT_INTERVAL
FROM DBA_SCHEDULER_JOBS
WHERE OWNER LIKE ('APP%') AND ENABLED = 'TRUE'
ORDER BY OWNER, JOB_NAME;
