ALTER SESSION SET NLS_LANGUAGE = 'BRAZILIAN PORTUGUESE';
ALTER SESSION SET NLS_TERRITORY = 'BRAZIL';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';

SELECT TO_CHAR( W.LOGON_TIME,'DD/MM/YY HH24:MI') LOGON_TIME, W.OSUSER, W.STATUS,  W.USERNAME, W.PROGRAM, W.CPU_USAGE, A.SQL_TEXT,
'EXEC RDSADMIN.RDSADMIN_UTIL.KILL('||W.SID||','||W.SERIAL#||','||''''||'IMMEDIATE'||''''||');' AWS_KILLSESSION,
'ALTER SYSTEM KILL SESSION '''||W.SID||',' || W.SERIAL#||',@'||W.INST_ID||''' IMMEDIATE;' ORA_KILLSESSION
FROM (SELECT S.LOGON_TIME, S.SQL_ADDRESS, S.SQL_HASH_VALUE, S.INST_ID, S.OSUSER, S.STATUS,  S.SID,  S.SERIAL#, S.USERNAME, S.PROGRAM, 
SUM(T.VALUE/100) AS CPU_USAGE FROM GV$SESSION S
INNER JOIN GV$SESSTAT T ON T.SID = S.SID 
INNER JOIN GV$STATNAME N ON T.STATISTIC# = N.STATISTIC#
WHERE N.NAME like '%CPU used by this session%' AND S.STATUS='ACTIVE' AND S.USERNAME IS NOT NULL
GROUP BY S.LOGON_TIME, S.SQL_ADDRESS, S.SQL_HASH_VALUE, s.inst_id, S.OSUSER, S.STATUS,  S.SID,  S.SERIAL#, S.USERNAME, S.PROGRAM
ORDER BY SUM(VALUE/100) DESC) W
INNER JOIN GV$SQLAREA A ON W.SQL_ADDRESS = A.ADDRESS  AND W.SQL_HASH_VALUE=A.HASH_VALUE;






