
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
ALTER SESSION SET NLS_LANGUAGE = 'BRAZILIAN PORTUGUESE';
ALTER SESSION SET NLS_TERRITORY = 'BRAZIL';

SELECT DBAUDIT_DATE, TO_CHAR(TO_DATE(DBAUDIT_DATE,'DD/MM/YYYY HH24:MI'),'DAY') DIASEMANA,
DBAUDIT_OSUSER, DBAUDIT_IPADDRESS, DBAUDIT_MACHINE, DBAUDIT_DATABASE,
DBAUDIT_MODULE, DBAUDIT_OBJECT_OWNER, DBAUDIT_OBJECT_NAME, DBAUDIT_SQL_TEXT
FROM DBAUDIT.DBAUDIT_DDL_LOG
ORDER BY TO_DATE(DBAUDIT_DATE,'DD/MM/YYYY HH24:MI') DESC;

CREATE USER DBAUDIT
IDENTIFIED BY 
DEFAULT TABLESPACE TBS_DBAUDIT_DAT
TEMPORARY TABLESPACE TEMP;

ALTER USER DBAUDIT QUOTA UNLIMITED ON TBS_DBAUDIT_DAT;
GRANT CONNECT, RESOURCE TO DBAUDIT;
GRANT DBA TO DBAUDIT;

CREATE TABLE DBAUDIT.DBAUDIT_DDL_LOG(
DBAUDIT_DATE VARCHAR2(100), 
DBAUDIT_OSUSER VARCHAR2(50), 
DBAUDIT_IPADDRESS VARCHAR2(50),
DBAUDIT_MACHINE VARCHAR2(100),
DBAUDIT_INSTANCE INTEGER, 
DBAUDIT_DATABASE VARCHAR2(50), 
DBAUDIT_MODULE VARCHAR2(1000),
DBAUDIT_OBJECT_OWNER VARCHAR2(100),
DBAUDIT_OBJECT_TYPE VARCHAR2(100), 
DBAUDIT_OBJECT_NAME VARCHAR2(100), 
DBAUDIT_SQL_TEXT VARCHAR2(4000));

CREATE INDEX DBAUDIT.DBAUDIT_DDL_LOG_IDX01 ON DBAUDIT.DBAUDIT_DDL_LOG (DBAUDIT_DATE);
CREATE INDEX DBAUDIT.DBAUDIT_DDL_LOG_IDX02 ON DBAUDIT.DBAUDIT_DDL_LOG (DBAUDIT_OSUSER);
CREATE INDEX DBAUDIT.DBAUDIT_DDL_LOG_IDX03 ON DBAUDIT.DBAUDIT_DDL_LOG (DBAUDIT_OBJECT_OWNER);


CREATE OR REPLACE TRIGGER DBAUDIT.DBAUDIT_DDL_LOG
AFTER DDL ON DATABASE
DECLARE
DDL_SQL_TEXT ORA_NAME_LIST_T;
DDL_COUNT NUMBER;
DDL_OSUSER VARCHAR2(50) := NULL;
DDL_IPADDRESS VARCHAR2(50) := NULL;
DDL_MACHINE VARCHAR2(100) := NULL;
DDL_MODULE VARCHAR2(1000) := NULL;
DDL_SQL VARCHAR2(4000);
BEGIN
DDL_COUNT := ORA_SQL_TXT(DDL_SQL_TEXT);
DDL_OSUSER := SUBSTR(TRIM(SYS_CONTEXT('USERENV','OS_USER')),1,50);
DDL_IPADDRESS := SUBSTR(TRIM(SYS_CONTEXT('USERENV','IP_ADDRESS')),1,50);
DDL_MACHINE := SUBSTR(TRIM(SYS_CONTEXT('USERENV','HOST')),1,100);
DDL_MODULE := SUBSTR(TRIM(SYS_CONTEXT('USERENV','MODULE')),1,1000);

DDL_COUNT := ORA_SQL_TXT(DDL_SQL_TEXT);
FOR I IN 1..DDL_COUNT LOOP
DDL_SQL := DDL_SQL||DDL_SQL_TEXT(I);
END LOOP;

IF DDL_SQL NOT LIKE '%REBUILD%' AND TRIM(ORA_DICT_OBJ_NAME) NOT LIKE '%ORA_TEMP%'
AND TRIM(DDL_OSUSER) != 'oracle' AND DDL_IPADDRESS IS NOT NULL THEN
 INSERT INTO DBAUDIT.DBAUDIT_DDL_LOG (DBAUDIT_DATE, DBAUDIT_OSUSER, DBAUDIT_IPADDRESS, DBAUDIT_MACHINE, DBAUDIT_INSTANCE, DBAUDIT_DATABASE, 
 DBAUDIT_MODULE, DBAUDIT_OBJECT_OWNER, DBAUDIT_OBJECT_TYPE,  DBAUDIT_OBJECT_NAME, DBAUDIT_SQL_TEXT)
 VALUES (TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'), DDL_OSUSER,DDL_IPADDRESS, DDL_MACHINE, ORA_INSTANCE_NUM,ORA_DATABASE_NAME, DDL_MODULE,
 SUBSTR(TRIM(ORA_DICT_OBJ_OWNER),1,100), SUBSTR(TRIM(ORA_DICT_OBJ_TYPE),1,100),SUBSTR(TRIM(ORA_DICT_OBJ_NAME),1,100),DDL_SQL);
END IF;

EXCEPTION
WHEN OTHERS THEN NULL;
END;


