ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
ALTER SESSION SET NLS_LANGUAGE = 'BRAZILIAN PORTUGUESE';
ALTER SESSION SET NLS_TERRITORY = 'BRAZIL';

SELECT S.INST_ID, B.STATE, A.OWNER , A.JOB_NAME, A.ELAPSED_TIME, B.REPEAT_INTERVAL,  B.JOB_ACTION, S.PROGRAM, S.MODULE,
'ALTER SYSTEM KILL SESSION '''||S.SID||',' || S.SERIAL#||',@'||S.INST_ID||''' IMMEDIATE;' CMD_KILLSESSION,
'EXEC RDSADMIN.RDSADMIN_UTIL.KILL('||S.SID||','||S.SERIAL#||','||''''||'IMMEDIATE'||''''||');' AWS_KILLSESSION
FROM DBA_SCHEDULER_RUNNING_JOBS A
INNER JOIN GV$SESSION S ON S.SID = A. SESSION_ID
INNER JOIN DBA_SCHEDULER_JOBS B ON A.OWNER = B.OWNER AND A.JOB_NAME = B.JOB_NAME
WHERE JOB_ACTION IS NOT NULL
ORDER BY ELAPSED_TIME DESC; 
