AWSTemplateFormatVersion: '2010-09-09'
Description: RDS Instance


Parameters:

  AllowMajorVersionUpgrade:
    Description: AllowMajorVersionUpgrade
    Type: String
    AllowedValues: [true, false]

  AutoMinorVersionUpgrade:
    Description: AutoMinorVersionUpgrade
    Type: String
    AllowedValues: [true, false]
    Default: true

  BackupRetentionPeriod:
    Description: The number of days during which automatic DB snapshots are retained.
    Type: String
    AllowedPattern: "^([0-9]{1}|[1-2]{1}[0-9]{1}|3[0-5]{1})$"

  DBInstanceClass:
    Description: DBInstanceClass
    Type: String
    Default: db.t2.small
    
  DBName:
    Description: The name of the database inside the instance.
    Type: String
  
  
  DBClusterIdentifier:
    Description: Name of the database cluster.
    Type: String
    AllowedPattern: "^[([a-z]|\\d|\\-)]{1,63}$"
  
  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    AllowedValues: [aurora, aurora-mysql, aurora-postgresql]

  VPCSecurityGroups:
    Description: Specifies if the database instance is a multiple Availability Zone deployment.
    Type: List<AWS::EC2::SecurityGroup::Id>
    ConstraintDescription: "Please provide valid ids for the security group(s)."

  MasterUsername:
    Description: The master user name for the DB instance.
    Type: String

  MasterUserPassword:
    Description: The master password for the DB instance.
    Type: String
    NoEcho: true


Mappings:

  ParameterGroupMapping:
    aurora:
      default: default.aurora5.6
    aurora-mysql:
      default: default.aurora-mysql5.7
    aurora-postgresql:
      default: default.aurora-postgresql9.6

Resources:  

  RDSDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DatabaseName: !Ref DBName
      DBClusterIdentifier: !Ref DBClusterIdentifier
      DBClusterParameterGroupName: !FindInMap [ParameterGroupMapping, !Ref Engine , default]
      Engine: !Ref Engine
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      VpcSecurityGroupIds: !Ref VPCSecurityGroups
      Tags:
        - Key: Name
          Value: !Sub
            - ${AWS::StackName}-${Name}
            - { Name: !Ref DBName }

  RDSInstance:  
    Type: AWS::RDS::DBInstance
    Properties:
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      DBInstanceClass: !Ref DBInstanceClass
      DBClusterIdentifier: !Ref RDSDBCluster
      Engine: !Ref Engine
      PubliclyAccessible: false 
      Tags:
        - Key: Name
          Value: !Sub
            - ${AWS::StackName}-${Name}
            - { Name: !Ref DBName }
    DependsOn: RDSDBCluster
    
  RDSInstance2:  
    Type: AWS::RDS::DBInstance
    Properties:
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      DBInstanceClass: !Ref DBInstanceClass
      DBClusterIdentifier: !Ref RDSDBCluster
      Engine: !Ref Engine
      PubliclyAccessible: false 
      Tags:
        - Key: Name
          Value: !Sub
            - ${AWS::StackName}-${Name}
            - { Name: !Ref DBName }
    DependsOn: RDSDBCluster

Outputs:
  DBInstanceIdentifier:
    Description: The database instance identifier
    Value: !Ref RDSInstance
    Export:
      Name: !Sub 
      - "${AWS::StackName}-${engine}-${Name}-identifier"
      - { Name: !Ref DBName, engine: !Ref Engine }

  DBEndpoint:
    Description: The connection endpoint for the database.
    Value: !GetAtt  RDSInstance.Endpoint.Address
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-${Name}-endpoint"
        - { Name: !Ref DBName, engine: !Ref Engine }

  DBPort:
    Description: The port number on which the database accepts connections.
    Value: !GetAtt  RDSInstance.Endpoint.Port
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-${Name}-port"
        - { Name: !Ref DBName, engine: !Ref Engine }
  
  
  RRInstanceIdentifier:
    Description: The database instance identifier
    Value: !Ref RDSInstance2
    Export:
      Name: !Sub 
      - "${AWS::StackName}-${engine}-${Name}-readreplica-identifier"
      - { Name: !Ref DBName, engine: !Ref Engine }

  RREndpoint:
    Description: The connection endpoint for the database.
    Value: !GetAtt  RDSInstance2.Endpoint.Address
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-${Name}-readreplica-endpoint"
        - { Name: !Ref DBName, engine: !Ref Engine }

  RRPort:
    Description: The port number on which the database accepts connections.
    Value: !GetAtt  RDSInstance2.Endpoint.Port
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-${Name}-readreplica-port"
        - { Name: !Ref DBName, engine: !Ref Engine } 
